import { useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Link } from "wouter";
import { ArrowDownLeft, ArrowDownRight, ArrowUpRight, CandlestickChart, ChevronRight, CircleCheck, Clock3, Info, LockKeyhole, ShieldCheck, TrendingUp, WalletCards } from "lucide-react";
import { useMarketStream } from "@/hooks/useMarketStream";
import { MarketStreamStatus } from "@/components/MarketStreamStatus";
import { toast } from "sonner";

const money = (value: string | number, currency = "USD") => new Intl.NumberFormat("fr-FR", { style: "currency", currency, maximumFractionDigits: 2 }).format(Number(value));
const forexRate = (value: string | number) => Number(value).toLocaleString("fr-FR", { minimumFractionDigits: Number(value) >= 100 ? 2 : 4, maximumFractionDigits: Number(value) >= 100 ? 2 : 4 });

export default function Home() {
  const { user } = useAuth();
  const { data, isLoading } = trpc.dashboard.summary.useQuery(undefined, { enabled: Boolean(user) });
  const marketStream = useMarketStream(Boolean(user));
  const { data: marketCatalog = [] } = trpc.market.catalog.useQuery({ query: "", assetClass: "all" }, { enabled: Boolean(user), staleTime: 30000 });
  const dashboardQuotes = marketStream.quoteList.length ? marketStream.quoteList : marketCatalog.slice(0, 4).map(item => ({ ...item, id: Number(item.id), price: String(item.price), changePercent: String(item.changePercent), asOf: Date.now() }));
  const forexQuotes = (marketStream.quoteList.length ? marketStream.quoteList : marketCatalog.map(item => ({ ...item, id: Number(item.id), price: String(item.price), changePercent: String(item.changePercent), asOf: Date.now() }))).filter(item => item.assetClass === "fx_spot");
  const [selectedForex, setSelectedForex] = useState<any>(null);
  const [forexSide, setForexSide] = useState<"buy" | "sell">("buy");
  const [forexQuantity, setForexQuantity] = useState("1");
  const utils = trpc.useUtils();
  const order = trpc.orders.placeSpot.useMutation({ onSuccess: result => { toast.success(result.message); setSelectedForex(null); void utils.dashboard.summary.invalidate(); }, onError: error => toast.error(error.message) });
  const selectedForexPrice = Number(selectedForex?.price ?? 0);
  const forexNotional = selectedForexPrice * Number(forexQuantity || 0);
  const wallets = data?.wallets ?? [];
  const usd = wallets.find(wallet => wallet.currency === "USD");
  const cdf = wallets.find(wallet => wallet.currency === "CDF");
  const selectedForexWallet = wallets.find(wallet => wallet.currency === selectedForex?.quoteCurrency);
  const tradeBlockedReason = data?.kyc?.status !== "approved" ? "Votre compte doit être approuvé par la conformité avant toute opération." : Number(selectedForexWallet?.availableBalance ?? 0) < forexNotional ? `Solde disponible insuffisant (${selectedForexWallet?.availableBalance ?? "0"} ${selectedForex?.quoteCurrency ?? "USD"}).` : "";
  const kycLabel = data?.kyc?.status === "approved" ? "Vérification approuvée" : "Vérification à compléter";

  return <div className="min-h-screen bg-[#f7f7f2] px-4 py-6 text-[#0a2233] sm:px-8 lg:px-10"><div className="mx-auto max-w-[1500px]">
    <header className="border-b border-[#dce4e5] pb-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="atg-kicker flex items-center gap-2 text-[#087f78]"><span className="h-1.5 w-1.5 bg-[#e6b93f]" />Marché en mode sécurisé</div><h1 className="atg-section-title mt-3 font-extrabold">Bonjour, {user?.name?.split(" ")[0] || "investisseur"}.</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-[#587086]">Une vue simple et contrôlée de vos investissements, de vos liquidités et des décisions qui nécessitent votre attention.</p></div><div className="flex flex-wrap items-center gap-3"><Badge className="border border-[#b9ded4] bg-[#e9f6f2] px-3 py-1.5 text-[#087f78]"><LockKeyhole className="mr-1.5 h-3.5 w-3.5" />Session protégée</Badge><Button asChild className="rounded-lg bg-[#0a2233] font-bold text-white hover:bg-[#0d2638]"><Link href="/market">Explorer les marchés<ChevronRight className="ml-1.5 h-4 w-4" /></Link></Button></div></div></header>
    <ForexTicker quotes={forexQuotes} onTrade={(quote, side) => { setForexSide(side); setSelectedForex(quote); setForexQuantity("1"); }} />
    <div className="mt-7 grid gap-px overflow-hidden border border-[#dce4e5] bg-[#dce4e5] sm:grid-cols-2 xl:grid-cols-4"><Metric title="Valeur du portefeuille" value={money(0)} note="USD consolidé" icon={<TrendingUp className="h-5 w-5" />} /><Metric title="Liquidités USD" value={isLoading ? "…" : money(usd?.availableBalance ?? 0)} note="Solde disponible" icon={<WalletCards className="h-5 w-5" />} accent /><Metric title="Liquidités CDF" value={isLoading ? "…" : money(cdf?.availableBalance ?? 0, "CDF")} note="Solde disponible" icon={<ArrowDownLeft className="h-5 w-5" />} /><Metric title="Positions ouvertes" value={String(data?.positions?.length ?? 0).padStart(2, "0")} note="Actions & spot FX" icon={<CandlestickChart className="h-5 w-5" />} /></div>
    <Card className="mt-7 rounded-none border-[#dce4e5] bg-white shadow-[0_18px_55px_rgba(7,26,42,.05)]"><CardContent className="p-5 sm:p-7"><div className="flex flex-col gap-4 border-b border-[#dce4e5] pb-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="atg-kicker text-[#087f78]">Marché en temps réel</p><div className="mt-2 flex items-center gap-2"><h2 className="text-lg font-extrabold text-[#0a2233]">Les instruments que vous pouvez suivre</h2><span className="hidden border border-[#dce4e5] px-2 py-1 text-[10px] font-extrabold uppercase tracking-[.12em] text-[#587086] sm:inline">WebSocket</span></div><p className="mt-1 text-sm text-[#587086]">Les dernières données reçues sont affichées sans activer l’exécution.</p></div><MarketStreamStatus connection={marketStream.connection} providerState={marketStream.providerState} message={marketStream.providerMessage} lastUpdate={marketStream.lastUpdate} compact /></div><div className="mt-5 grid gap-px overflow-hidden border border-[#dce4e5] bg-[#dce4e5] sm:grid-cols-2 xl:grid-cols-4">{dashboardQuotes.slice(0, 4).map(quote => <div key={quote.symbol} className="min-w-0 bg-[#f7f7f2] p-4"><div className="flex items-center justify-between gap-2"><span className="font-extrabold text-[#0a2233]">{quote.symbol}</span><span className={`text-xs font-bold ${Number(quote.changePercent) >= 0 ? "text-[#087f78]" : "text-[#bb6e6e]"}`}>{Number(quote.changePercent) >= 0 ? "+" : ""}{quote.changePercent}%</span></div><p className="atg-mono mt-3 text-lg font-extrabold text-[#0a2233]">{quote.price} <span className="text-xs font-normal text-[#587086]">{quote.quoteCurrency}</span></p><p className="mt-1 text-[11px] text-[#587086]">{quote.assetClass === "equity" ? "Action" : "Forex spot"}</p></div>)}{dashboardQuotes.length === 0 && <div className="bg-[#f7f7f2] p-4 text-sm text-[#587086] sm:col-span-2 xl:col-span-4">Le catalogue de marché se synchronisera dès que le flux sera disponible.</div>}</div></CardContent></Card>
    <div className="mt-7 grid gap-7 xl:grid-cols-[1.45fr_.8fr]"><Card className="overflow-hidden rounded-none border-0 bg-[#071a2a] text-white shadow-[0_22px_65px_rgba(7,26,42,.15)]"><CardHeader className="flex flex-row items-start justify-between border-b border-white/10 pb-5"><div><p className="atg-kicker text-[#7ddcca]">Allocation</p><CardTitle className="mt-2 text-xl font-extrabold">Portefeuille consolidé</CardTitle></div><Badge className="border border-white/15 bg-white/10 text-slate-200">CDF / USD</Badge></CardHeader><CardContent className="pt-6"><div className="grid gap-8 md:grid-cols-[.85fr_1.15fr] md:items-end"><div><p className="atg-mono text-5xl font-extrabold tracking-[-.07em]">{money(0)}</p><p className="mt-3 text-sm leading-6 text-slate-400">Valeur indicative en connexion des partenaires en cours</p><div className="mt-7 flex items-center gap-2 text-sm font-bold text-[#e6b93f]"><CircleCheck className="h-4 w-4" />Aucune exécution réelle connectée</div></div><div className="space-y-4"><AllocationBar label="Liquidités" value="100%" width="100%" color="bg-[#e6b93f]" /><AllocationBar label="Actions" value="0%" width="0%" color="bg-[#18b89a]" /><AllocationBar label="Spot FX" value="0%" width="0%" color="bg-[#79cbd4]" /></div></div></CardContent></Card>
      <Card className="rounded-none border-[#dce4e5] bg-white shadow-[0_18px_55px_rgba(7,26,42,.05)]"><CardHeader className="flex flex-row items-start justify-between border-b border-[#dce4e5] pb-5"><div><p className="atg-kicker text-[#587086]">Conformité</p><CardTitle className="mt-2 text-xl font-extrabold text-[#0a2233]">Votre compte</CardTitle></div><ShieldCheck className="h-5 w-5 text-[#087f78]" /></CardHeader><CardContent className="pt-6"><div className="border-l-2 border-[#18b89a] bg-[#e9f6f2] p-4"><div className="flex items-start gap-3"><div className="mt-0.5 text-[#087f78]"><ShieldCheck className="h-4 w-4" /></div><div><p className="text-sm font-extrabold text-[#0a2233]">{kycLabel}</p><p className="mt-1 text-xs leading-5 text-[#587086]">Le trading réel est activé uniquement après validation KYC/AML-CFT et approbation des partenaires.</p></div></div><Button asChild variant="outline" className="mt-4 w-full rounded-lg border-[#087f78]/30 bg-transparent text-[#087f78] hover:bg-white"><Link href="/activity">Voir le statut<ChevronRight className="ml-auto h-4 w-4" /></Link></Button></div><div className="mt-5 flex items-center gap-3 border-t border-[#dce4e5] pt-5"><Clock3 className="h-4 w-4 text-[#587086]" /><p className="text-xs leading-5 text-[#587086]">Les demandes de dépôt, retrait et ordre sont journalisées pour votre sécurité.</p></div></CardContent></Card></div>
    <div className="mt-7 grid gap-px overflow-hidden border border-[#dce4e5] bg-[#dce4e5] sm:grid-cols-3"><QuickAction href="/wallets" icon={<ArrowDownLeft />} title="Déposer" text="Créer une demande" /><QuickAction href="/wallets" icon={<ArrowUpRight />} title="Retirer" text="Soumettre au contrôle" /><QuickAction href="/market" icon={<CandlestickChart />} title="Passer un ordre" text="Actions & spot FX" /></div>
    <Dialog open={Boolean(selectedForex)} onOpenChange={open => !open && setSelectedForex(null)}><DialogContent className="rounded-2xl border-[#dce4e5] bg-[#f7f7f2] text-[#0a2233] shadow-[0_24px_80px_rgba(7,26,42,.28)] sm:max-w-md"><DialogHeader><DialogTitle className="font-extrabold text-[#0a2233]">Trade rapide · {selectedForex?.symbol}</DialogTitle><DialogDescription>{selectedForex?.name} · {selectedForex?.baseCurrency}/{selectedForex?.quoteCurrency}</DialogDescription></DialogHeader><div className="border-l-2 border-[#e6b93f] bg-white p-4"><div className="flex items-center justify-between"><span className="text-sm text-[#587086]">Cours indicatif</span><span className="atg-mono font-extrabold text-[#0a2233]">{forexRate(selectedForexPrice)} {selectedForex?.quoteCurrency}</span></div><div className="mt-3 flex items-center justify-between"><span className="text-sm text-[#587086]">Risque</span><Badge className="bg-[#fff2d9] text-[#94681f]">{selectedForex?.riskLevel}</Badge></div></div><div className="grid grid-cols-2 gap-2"><Button onClick={() => setForexSide("buy")} className={forexSide === "buy" ? "rounded-lg bg-[#087f78] text-white" : "rounded-lg bg-[#e5f2ef] text-[#087f78] hover:bg-[#d9ece7]"}>Acheter</Button><Button onClick={() => setForexSide("sell")} className={forexSide === "sell" ? "rounded-lg bg-[#bb6e6e] text-white" : "rounded-lg bg-[#f5e7e7] text-[#bb6e6e] hover:bg-[#f0d9d9]"}>Vendre</Button></div><div><label className="text-xs font-semibold text-[#587086]">Quantité</label><Input type="number" min="0.0001" step="0.0001" value={forexQuantity} onChange={event => setForexQuantity(event.target.value)} className="mt-2 border-[#dce4e5] bg-white" /></div><div className="flex items-center justify-between border-t border-[#dce4e5] pt-3 text-sm"><span className="text-[#587086]">Valeur indicative</span><span className="atg-mono font-extrabold text-[#0a2233]">{forexRate(forexNotional)} {selectedForex?.quoteCurrency}</span></div><p className="text-xs leading-5 text-[#587086]"><Info className="mr-1 inline h-3.5 w-3.5" />La demande reste en attente jusqu’à l’activation d’un partenaire agréé.</p>{tradeBlockedReason && <p className="border border-amber-200 bg-amber-50 p-3 text-xs leading-5 text-amber-800">{tradeBlockedReason}</p>}<DialogFooter><Button disabled={order.isPending || Boolean(tradeBlockedReason)} onClick={() => order.mutate({ instrumentId: Number(selectedForex.id), symbol: selectedForex.symbol, side: forexSide, orderType: "market", quantity: Number(forexQuantity), idempotencyKey: crypto.randomUUID() })} className="w-full rounded-lg bg-[#0a2233] text-white hover:bg-[#0d2638]">{order.isPending ? "Validation…" : tradeBlockedReason ? "Trading indisponible" : `Confirmer ${forexSide === "buy" ? "l’achat" : "la vente"}`}</Button></DialogFooter></DialogContent></Dialog>
  </div></div>;
}

function ForexTicker({ quotes, onTrade }: { quotes: any[]; onTrade: (quote: any, side: "buy" | "sell") => void }) { return <section aria-label="Instruments forex rapides" className="mt-5 overflow-hidden border border-[#dce4e5] bg-white shadow-[0_12px_35px_rgba(7,26,42,.04)]"><div className="flex items-center justify-between border-b border-[#dce4e5] px-4 py-3 sm:px-5"><div><p className="atg-kicker text-[#087f78]">Forex spot</p><p className="mt-1 text-xs text-[#587086]">Cours indicatifs · Trade rapide</p></div><Link href="/market" className="text-xs font-extrabold text-[#087f78] hover:underline">Voir tous les marchés</Link></div><div className="grid grid-cols-2 gap-px bg-[#dce4e5] sm:grid-cols-3 lg:grid-cols-4">{quotes.length ? quotes.map(quote => { const positive = Number(quote.changePercent) >= 0; return <div key={quote.symbol} className="min-w-0 bg-[#f7f7f2] p-3 sm:p-4"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="truncate font-extrabold text-[#0a2233]">{quote.symbol}</p><p className="mt-1 text-[10px] text-[#587086]">{quote.baseCurrency}/{quote.quoteCurrency}</p></div><span className={`flex shrink-0 items-center gap-0.5 text-[11px] font-extrabold ${positive ? "text-[#087f78]" : "text-[#bb6e6e]"}`}>{positive ? <ArrowUpRight className="h-3.5 w-3.5" /> : <ArrowDownRight className="h-3.5 w-3.5" />}{positive ? "+" : ""}{quote.changePercent}%</span></div><p className="atg-mono mt-3 text-lg font-extrabold text-[#0a2233]">{forexRate(quote.price)} <span className="text-[10px] font-normal text-[#587086]">{quote.quoteCurrency}</span></p><Button size="sm" onClick={() => onTrade(quote, positive ? "buy" : "sell")} className="mt-3 h-8 w-full rounded-lg bg-[#0a2233] text-xs font-bold text-white hover:bg-[#0d2638]">Trade <ChevronRight className="ml-1 h-3.5 w-3.5" /></Button></div>; }) : <p className="bg-[#f7f7f2] px-2 py-4 text-sm text-[#587086]">Les taux forex apparaîtront dès que le catalogue est disponible.</p>}</div></section>; }
function Metric({ title, value, note, icon, accent = false }: { title: string; value: string; note: string; icon: React.ReactNode; accent?: boolean }) { return <Card className={`rounded-none border-0 shadow-none ${accent ? "bg-[#e9f6f2]" : "bg-white"}`}><CardContent className="p-5"><div className="flex items-center justify-between"><span className={`grid h-10 w-10 place-items-center ${accent ? "bg-[#cbe9e1] text-[#087f78]" : "bg-[#e9eef0] text-[#087f78]"}`}>{icon}</span><span className="atg-kicker text-[#587086]">Africoin</span></div><p className="mt-5 text-xs text-[#587086]">{title}</p><p className="atg-mono mt-1 text-2xl font-extrabold text-[#0a2233]">{value}</p><p className="mt-1 text-xs text-[#587086]">{note}</p></CardContent></Card>; }
function QuickAction({ href, icon, title, text }: { href: string; icon: React.ReactNode; title: string; text: string }) { return <Link href={href} className="group bg-white p-5 transition hover:bg-[#e9f6f2]"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center bg-[#e5f2ef] text-[#087f78]">{icon}</span><ChevronRight className="h-4 w-4 text-[#9ab0bc] transition group-hover:translate-x-1 group-hover:text-[#087f78]" /></div><p className="mt-5 font-extrabold text-[#0a2233]">{title}</p><p className="mt-1 text-sm text-[#587086]">{text}</p></Link>; }
function AllocationBar({ label, value, width, color }: { label: string; value: string; width: string; color: string }) { return <div><div className="flex items-center justify-between text-xs text-slate-400"><span>{label}</span><span>{value}</span></div><div className="mt-2 h-1.5 overflow-hidden bg-white/10"><div className={`h-full ${color}`} style={{ width }} /></div></div>; }
