import { useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Link } from "wouter";
import { ArrowDownLeft, ArrowDownRight, ArrowUpRight, CandlestickChart, ChevronRight, CircleCheck, Clock3, Info, LockKeyhole, ShieldCheck, TrendingUp, WalletCards } from "lucide-react";
import { useMarketStream } from "@/hooks/useMarketStream";
import { MarketStreamStatus } from "@/components/MarketStreamStatus";
import { toast } from "sonner";

const money = (value: string | number, currency = "USD") => new Intl.NumberFormat("fr-FR", { style: "currency", currency, maximumFractionDigits: 2 }).format(Number(value));
const forexRate = (value: string | number) => Number(value).toLocaleString("fr-FR", { minimumFractionDigits: Number(value) >= 100 ? 2 : 4, maximumFractionDigits: Number(value) >= 100 ? 2 : 4 });

export default function Home() {
  const { user } = useAuth();
  const { data, isLoading } = trpc.dashboard.summary.useQuery(undefined, { enabled: Boolean(user) });
  const marketStream = useMarketStream(Boolean(user));
  const { data: marketCatalog = [] } = trpc.market.catalog.useQuery({ query: "", assetClass: "all" }, { enabled: Boolean(user), staleTime: 30000 });
  const dashboardQuotes = marketStream.quoteList.length ? marketStream.quoteList : marketCatalog.slice(0, 4).map(item => ({ ...item, id: Number(item.id), price: String(item.price), changePercent: String(item.changePercent), asOf: Date.now() }));
  const forexQuotes = (marketStream.quoteList.length ? marketStream.quoteList : marketCatalog.map(item => ({ ...item, id: Number(item.id), price: String(item.price), changePercent: String(item.changePercent), asOf: Date.now() }))).filter(item => item.assetClass === "fx_spot");
  const [selectedForex, setSelectedForex] = useState<any>(null);
  const [forexSide, setForexSide] = useState<"buy" | "sell">("buy");
  const [forexQuantity, setForexQuantity] = useState("1");
  const utils = trpc.useUtils();
  const order = trpc.orders.placeSpot.useMutation({ onSuccess: result => { toast.success(result.message); setSelectedForex(null); void utils.dashboard.summary.invalidate(); }, onError: error => toast.error(error.message) });
  const selectedForexPrice = Number(selectedForex?.price ?? 0);
  const forexNotional = selectedForexPrice * Number(forexQuantity || 0);
  const wallets = data?.wallets ?? [];
  const usd = wallets.find(wallet => wallet.currency === "USD");
  const cdf = wallets.find(wallet => wallet.currency === "CDF");
  const selectedForexWallet = wallets.find(wallet => wallet.currency === selectedForex?.quoteCurrency);
  const tradeBlockedReason = data?.kyc?.status !== "approved" ? "Votre compte doit être approuvé par la conformité avant toute opération." : Number(selectedForexWallet?.availableBalance ?? 0) < forexNotional ? `Solde disponible insuffisant (${selectedForexWallet?.availableBalance ?? "0"} ${selectedForex?.quoteCurrency ?? "USD"}).` : "";
  const kycLabel = data?.kyc?.status === "approved" ? "Vérification approuvée" : "Vérification à compléter";

  return <div className="min-h-screen bg-[#f5f7f5] px-4 py-6 sm:px-8 lg:px-10"><div className="mx-auto max-w-[1500px]">
    <header className="flex flex-col gap-5 border-b border-slate-200 pb-6 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.22em] text-[#6b8e23]"><span className="h-2 w-2 rounded-full bg-[#e6b84d]" />Marché en mode sécurisé</div><h1 className="mt-3 text-3xl font-semibold tracking-tight text-[#0b1f2a] sm:text-4xl">Bonjour, {user?.name?.split(" ")[0] || "investisseur"}.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Une vue simple et contrôlée de vos investissements, de vos liquidités et des décisions qui nécessitent votre attention.</p></div><div className="flex items-center gap-3"><Badge className="border border-[#b8d970] bg-[#eef8d8] px-3 py-1.5 text-[#4c651d]"><LockKeyhole className="mr-1.5 h-3.5 w-3.5" />Session protégée</Badge><Button asChild className="bg-[#0b1f2a] text-white hover:bg-[#163747]"><Link href="/market">Explorer les marchés<ChevronRight className="ml-1.5 h-4 w-4" /></Link></Button></div></header>
    <ForexTicker quotes={forexQuotes} onTrade={(quote, side) => { setForexSide(side); setSelectedForex(quote); setForexQuantity("1"); }} />
    <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Valeur du portefeuille" value={money(0)} note="USD consolidé" icon={<TrendingUp className="h-5 w-5" />} /><Metric title="Liquidités USD" value={isLoading ? "…" : money(usd?.availableBalance ?? 0)} note="Solde disponible" icon={<WalletCards className="h-5 w-5" />} accent /><Metric title="Liquidités CDF" value={isLoading ? "…" : money(cdf?.availableBalance ?? 0, "CDF")} note="Solde disponible" icon={<ArrowDownLeft className="h-5 w-5" />} /><Metric title="Positions ouvertes" value={String(data?.positions?.length ?? 0).padStart(2, "0")} note="Actions & spot FX" icon={<CandlestickChart className="h-5 w-5" />} /></div>
    <Card className="mt-6 rounded-[24px] border border-slate-200 bg-white shadow-sm"><CardContent className="p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#698b2d]">Marché en temps réel</p><div className="mt-2 flex items-center gap-2"><h2 className="text-lg font-semibold text-[#0b1f2a]">Les instruments que vous pouvez suivre</h2><span className="hidden rounded-full bg-[#f1f5f2] px-2 py-1 text-[10px] font-semibold uppercase tracking-[0.12em] text-slate-400 sm:inline">WebSocket</span></div><p className="mt-1 text-sm text-slate-500">Les dernières données reçues sont affichées sans activer l’exécution.</p></div><MarketStreamStatus connection={marketStream.connection} providerState={marketStream.providerState} message={marketStream.providerMessage} lastUpdate={marketStream.lastUpdate} compact /></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{dashboardQuotes.slice(0, 4).map(quote => <div key={quote.symbol} className="rounded-2xl bg-[#f7faf6] p-4"><div className="flex items-center justify-between gap-2"><span className="font-semibold text-[#0b1f2a]">{quote.symbol}</span><span className={`text-xs font-medium ${Number(quote.changePercent) >= 0 ? "text-[#4d8d73]" : "text-[#bb6e6e]"}`}>{Number(quote.changePercent) >= 0 ? "+" : ""}{quote.changePercent}%</span></div><p className="mt-2 text-lg font-semibold text-[#0b1f2a]">{quote.price} <span className="text-xs font-normal text-slate-400">{quote.quoteCurrency}</span></p><p className="mt-1 text-[11px] text-slate-400">{quote.assetClass === "equity" ? "Action" : "Forex spot"}</p></div>)}{dashboardQuotes.length === 0 && <div className="rounded-2xl bg-[#f7faf6] p-4 text-sm text-slate-500 sm:col-span-2 xl:col-span-4">Le catalogue de marché se synchronisera dès que le flux sera disponible.</div>}</div></CardContent></Card>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.45fr_.8fr]">
      <Card className="overflow-hidden rounded-[24px] border-0 bg-[#0b1f2a] text-white shadow-[0_18px_60px_rgba(11,31,42,.13)]"><CardHeader className="flex flex-row items-start justify-between pb-3"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#20c9a5]">Allocation</p><CardTitle className="mt-2 text-xl font-medium">Portefeuille consolidé</CardTitle></div><Badge className="border border-white/10 bg-white/10 text-slate-200">CDF / USD</Badge></CardHeader><CardContent><div className="grid gap-7 md:grid-cols-[.85fr_1.15fr] md:items-end"><div><p className="text-5xl font-semibold tracking-tight">{money(0)}</p><p className="mt-2 text-sm text-slate-400">Valeur indicative en connexion des partenaires en cours</p><div className="mt-7 flex items-center gap-2 text-sm text-[#e6b84d]"><CircleCheck className="h-4 w-4" />Aucune exécution réelle connectée</div></div><div className="space-y-4"><div className="flex items-center justify-between text-xs text-slate-400"><span>Liquidités</span><span>100%</span></div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full w-full rounded-full bg-[#e6b84d]" /></div><div className="flex items-center justify-between text-xs text-slate-400"><span>Actions</span><span>0%</span></div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full w-0 rounded-full bg-[#73d2de]" /></div><div className="flex items-center justify-between text-xs text-slate-400"><span>Spot FX</span><span>0%</span></div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full w-0 rounded-full bg-[#f0bc72]" /></div></div></div></CardContent></Card>
      <Card className="rounded-[24px] border border-slate-200 bg-white shadow-sm"><CardHeader className="flex flex-row items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">Conformité</p><CardTitle className="mt-2 text-xl font-medium text-[#0b1f2a]">Votre compte</CardTitle></div><ShieldCheck className="h-5 w-5 text-[#86a83a]" /></CardHeader><CardContent><div className="rounded-2xl bg-[#f5f8f2] p-4"><div className="flex items-start gap-3"><div className="mt-0.5 rounded-full bg-[#dff2ae] p-1.5 text-[#59751e]"><ShieldCheck className="h-4 w-4" /></div><div><p className="text-sm font-semibold text-[#233b26]">{kycLabel}</p><p className="mt-1 text-xs leading-5 text-slate-500">Le trading réel est activé uniquement après validation KYC/AML-CFT et approbation des partenaires.</p></div></div><Button asChild variant="outline" className="mt-4 w-full border-[#a7d8cb] text-[#006b5c] hover:bg-[#f5f8f2]"><Link href="/activity">Voir le statut<ChevronRight className="ml-auto h-4 w-4" /></Link></Button></div><div className="mt-5 flex items-center gap-3 border-t border-slate-100 pt-5"><Clock3 className="h-4 w-4 text-slate-400" /><p className="text-xs leading-5 text-slate-500">Les demandes de dépôt, retrait et ordre sont journalisées pour votre sécurité.</p></div></CardContent></Card>
    </div>
    <div className="mt-6 grid gap-4 sm:grid-cols-3"><QuickAction href="/wallets" icon={<ArrowDownLeft />} title="Déposer" text="Créer une demande" /><QuickAction href="/wallets" icon={<ArrowUpRight />} title="Retirer" text="Soumettre au contrôle" /><QuickAction href="/market" icon={<CandlestickChart />} title="Passer un ordre" text="Actions & spot FX" /></div>
    <Dialog open={Boolean(selectedForex)} onOpenChange={open => !open && setSelectedForex(null)}><DialogContent className="rounded-[24px] border-slate-200 bg-white text-[#0b1f2a] shadow-[0_24px_80px_rgba(6,21,38,.28)] sm:max-w-md"><DialogHeader><DialogTitle className="text-[#0b1f2a]">Trade rapide · {selectedForex?.symbol}</DialogTitle><DialogDescription>{selectedForex?.name} · {selectedForex?.baseCurrency}/{selectedForex?.quoteCurrency}</DialogDescription></DialogHeader><div className="rounded-2xl bg-[#f5f8f2] p-4"><div className="flex items-center justify-between"><span className="text-sm text-slate-500">Cours indicatif</span><span className="font-semibold text-[#0b1f2a]">{forexRate(selectedForexPrice)} {selectedForex?.quoteCurrency}</span></div><div className="mt-3 flex items-center justify-between"><span className="text-sm text-slate-500">Risque</span><Badge className="bg-[#fff2d9] text-[#94681f]">{selectedForex?.riskLevel}</Badge></div></div><div className="grid grid-cols-2 gap-2"><Button onClick={() => setForexSide("buy")} className={forexSide === "buy" ? "bg-[#4d8d73] text-white" : "bg-slate-100 text-slate-600 hover:bg-slate-200"}>Acheter</Button><Button onClick={() => setForexSide("sell")} className={forexSide === "sell" ? "bg-[#bb6e6e] text-white" : "bg-slate-100 text-slate-600 hover:bg-slate-200"}>Vendre</Button></div><div><label className="text-xs font-medium text-slate-600">Quantité</label><Input type="number" min="0.0001" step="0.0001" value={forexQuantity} onChange={event => setForexQuantity(event.target.value)} className="mt-2" /></div><div className="flex items-center justify-between border-t border-slate-100 pt-3 text-sm"><span className="text-slate-500">Valeur indicative</span><span className="font-semibold text-[#0b1f2a]">{forexRate(forexNotional)} {selectedForex?.quoteCurrency}</span></div><p className="text-xs leading-5 text-slate-500"><Info className="mr-1 inline h-3.5 w-3.5" />La demande reste en attente jusqu’à l’activation d’un partenaire agréé.</p>{tradeBlockedReason && <p className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs leading-5 text-amber-800">{tradeBlockedReason}</p>}<DialogFooter><Button disabled={order.isPending || Boolean(tradeBlockedReason)} onClick={() => order.mutate({ instrumentId: Number(selectedForex.id), symbol: selectedForex.symbol, side: forexSide, orderType: "market", quantity: Number(forexQuantity), idempotencyKey: crypto.randomUUID() })} className="w-full bg-[#0b1f2a] text-white hover:bg-[#163747]">{order.isPending ? "Validation…" : tradeBlockedReason ? "Trading indisponible" : `Confirmer ${forexSide === "buy" ? "l’achat" : "la vente"}`}</Button></DialogFooter></DialogContent></Dialog>
  </div></div>;
}

function ForexTicker({ quotes, onTrade }: { quotes: any[]; onTrade: (quote: any, side: "buy" | "sell") => void }) { return <section aria-label="Instruments forex rapides" className="mt-5 overflow-hidden rounded-[22px] border border-[#d8e6c1] bg-[#f8fbf3] shadow-sm"><div className="flex items-center justify-between border-b border-[#e4edd6] px-4 py-3 sm:px-5"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#6b8e23]">Forex spot</p><p className="mt-1 text-xs text-slate-500">Cours indicatifs · Trade rapide</p></div><Link href="/market" className="text-xs font-semibold text-[#008f76] hover:underline">Voir tous les marchés</Link></div><div className="grid grid-cols-2 gap-2 p-3 sm:grid-cols-3 sm:gap-3 sm:p-4 lg:grid-cols-4">{quotes.length ? quotes.map(quote => { const positive = Number(quote.changePercent) >= 0; return <div key={quote.symbol} className="min-w-0 rounded-2xl border border-white bg-white p-3 shadow-sm"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="truncate font-semibold text-[#0b1f2a]">{quote.symbol}</p><p className="mt-1 text-[10px] text-slate-400">{quote.baseCurrency}/{quote.quoteCurrency}</p></div><span className={`flex shrink-0 items-center gap-0.5 text-[11px] font-semibold ${positive ? "text-[#4d8d73]" : "text-[#bb6e6e]"}`}>{positive ? <ArrowUpRight className="h-3.5 w-3.5" /> : <ArrowDownRight className="h-3.5 w-3.5" />}{positive ? "+" : ""}{quote.changePercent}%</span></div><p className="mt-2 text-lg font-semibold tracking-tight text-[#0b1f2a]">{forexRate(quote.price)} <span className="text-[10px] font-normal text-slate-400">{quote.quoteCurrency}</span></p><Button size="sm" onClick={() => onTrade(quote, positive ? "buy" : "sell")} className="mt-2 h-8 w-full bg-[#0b1f2a] text-xs text-white hover:bg-[#163747]">Trade <ChevronRight className="ml-1 h-3.5 w-3.5" /></Button></div>; }) : <p className="px-2 py-4 text-sm text-slate-500">Les taux forex apparaîtront dès que le catalogue est disponible.</p>}</div></section>; }

function Metric({ title, value, note, icon, accent = false }: { title: string; value: string; note: string; icon: React.ReactNode; accent?: boolean }) { return <Card className={`rounded-[22px] border-0 shadow-sm ${accent ? "bg-[#eff7dc]" : "bg-white"}`}><CardContent className="p-5"><div className="flex items-center justify-between"><span className={`grid h-10 w-10 place-items-center rounded-2xl ${accent ? "bg-[#d8ed9e] text-[#5d7b23]" : "bg-[#f1f5f2] text-[#6a8b31]"}`}>{icon}</span><span className="text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-400">Africoin</span></div><p className="mt-5 text-xs text-slate-500">{title}</p><p className="mt-1 text-2xl font-semibold tracking-tight text-[#0b1f2a]">{value}</p><p className="mt-1 text-xs text-slate-400">{note}</p></CardContent></Card>; }
function QuickAction({ href, icon, title, text }: { href: string; icon: React.ReactNode; title: string; text: string }) { return <Link href={href} className="group rounded-[22px] border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-[#bfd682] hover:shadow-md"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#e8f5f0] text-[#698b2d]">{icon}</span><ChevronRight className="h-4 w-4 text-slate-300 transition group-hover:translate-x-1 group-hover:text-[#698b2d]" /></div><p className="mt-5 font-semibold text-[#0b1f2a]">{title}</p><p className="mt-1 text-sm text-slate-500">{text}</p></Link>; }
