import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ArrowRight, BarChart3, Check, ChevronDown, ChevronRight, Globe2, LockKeyhole, Menu, ShieldCheck, Sparkles, WalletCards, X } from "lucide-react";
import { Link } from "wouter";
import { useState } from "react";

const logo = "/assets/branding/logoafricoin.jpeg";
const favicon = "/assets/branding/logoafricoin.jpeg";

const marketSignals = [
  { id: "actions", label: "Actions", eyebrow: "NASDAQ · NYSE", title: "Des instruments lisibles", text: "Symboles, devise, risque et informations essentielles réunis avant toute décision.", icon: BarChart3, accent: "gold" },
  { id: "forex", label: "Forex spot", eyebrow: "EURUSD · USDJPY", title: "Le change sans opacité", text: "Un espace spot clair, sans marge ni CFD activés par défaut.", icon: Globe2, accent: "teal" },
  { id: "wallets", label: "CDF / USD", eyebrow: "Liquidités · suivi", title: "Votre contexte avant l’action", text: "Un aperçu de vos devises, demandes et contrôles dans une même expérience.", icon: WalletCards, accent: "lime" },
] as const;

const faqs = [
  ["Les cotations affichées sont-elles déjà exécutables ?", "Non. Le catalogue public présente les marchés et les règles de lecture. Toute exécution reste soumise à la connexion d’un partenaire agréé, aux contrôles applicables et à la validation du parcours."],
  ["Quels sont les frais annoncés ?", "Les frais dépendent du canal, de la devise et du partenaire sélectionné. Les conditions applicables doivent être affichées avant confirmation ; AFRICOIN TRADING GROUP n’invente pas de montant fixe en amont."],
  ["Pourquoi le KYC est-il nécessaire ?", "La vérification d’identité et le profil de risque permettent d’appliquer les contrôles KYC/AML-CFT, les limites et les règles adaptées à votre situation avant l’accès aux fonctions sensibles."],
] as const;

export default function Landing() {
  const [mobileOpen, setMobileOpen] = useState(false);
  const [activeMarket, setActiveMarket] = useState<(typeof marketSignals)[number]["id"]>("actions");
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const activeSignal = marketSignals.find(signal => signal.id === activeMarket) ?? marketSignals[0];
  const ActiveIcon = activeSignal.icon;

  return <div className="min-h-screen overflow-hidden bg-[#f8faf7] text-[#0b1f2a] selection:bg-[#e6b84d]/30">
    <header className="relative z-20 border-b border-white/10 bg-[#061526]/95 text-white backdrop-blur-xl">
      <div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8">
        <Link href="/" className="flex items-center gap-3" aria-label="AFRICOIN TRADING GROUP accueil">
          <img src={favicon} alt="" className="h-10 w-10 rounded-xl border border-[#d9aa3f]/50" />
          <span><span className="block text-sm font-semibold tracking-tight">AFRICOIN <span className="text-[#e6b84d]">TRADING GROUP</span></span><span className="block text-[9px] uppercase tracking-[0.14em] text-[#20c9a5]">Les marchés numériques d’Afrique · ATG</span></span>
        </Link>
        <nav className="hidden items-center gap-7 text-sm text-slate-300 md:flex" aria-label="Navigation principale">
          <a href="#marches" className="transition-colors hover:text-white">Marchés</a><Link href="/tarifs-risques-conditions" className="transition-colors hover:text-white">Tarifs & risques</Link><a href="#parcours" className="transition-colors hover:text-white">Parcours</a><a href="#faq" className="transition-colors hover:text-white">FAQ</a>
        </nav>
        <div className="hidden items-center gap-3 md:flex"><Link href="/connexion" className="text-sm text-slate-300 transition hover:text-white">Se connecter</Link><Link href="/inscription" className="rounded-lg bg-[#e6b84d] px-4 py-2 text-sm font-semibold text-[#08131f] shadow-[0_8px_28px_rgba(230,184,77,.18)] transition hover:-translate-y-0.5 hover:bg-[#f3d27a]">Créer un compte</Link></div>
        <button className="grid h-10 w-10 place-items-center rounded-xl border border-white/10 transition hover:bg-white/10 md:hidden" onClick={() => setMobileOpen(value => !value)} aria-label={mobileOpen ? "Fermer le menu" : "Ouvrir le menu"} aria-expanded={mobileOpen}>{mobileOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</button>
      </div>
      {mobileOpen && <div className="border-t border-white/10 px-5 py-5 md:hidden"><div className="flex flex-col gap-4 text-sm text-slate-300"><a href="#marches" onClick={() => setMobileOpen(false)}>Marchés</a><Link href="/tarifs-risques-conditions" onClick={() => setMobileOpen(false)}>Tarifs & risques</Link><a href="#parcours" onClick={() => setMobileOpen(false)}>Parcours</a><a href="#faq" onClick={() => setMobileOpen(false)}>FAQ</a><Link href="/inscription" onClick={() => setMobileOpen(false)} className="mt-2 rounded-lg bg-[#e6b84d] px-4 py-3 text-center font-semibold text-[#08131f]">Créer un compte</Link></div></div>}
    </header>

    <main>
      <section className="relative isolate overflow-hidden bg-[#061526] pb-20 pt-16 text-white sm:pb-28 sm:pt-24">
        <div className="pointer-events-none absolute inset-0 -z-10 bg-[radial-gradient(circle_at_78%_10%,rgba(32,201,165,.24),transparent_28%),radial-gradient(circle_at_12%_40%,rgba(230,184,77,.16),transparent_28%)]" />
        <div className="pointer-events-none absolute inset-0 -z-10 opacity-25 [background-image:linear-gradient(rgba(255,255,255,.06)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.06)_1px,transparent_1px)] [background-size:64px_64px]" />
        <div className="mx-auto grid max-w-7xl items-center gap-14 px-5 sm:px-8 lg:grid-cols-[1.08fr_.92fr] lg:gap-16">
          <div className="relative">
            <Badge className="border-[#20c9a5]/30 bg-[#20c9a5]/10 text-[#86efd7]"><span className="mr-2 inline-block h-1.5 w-1.5 rounded-full bg-[#e6b84d] motion-safe:animate-pulse" />Marchés africains, nouvelle discipline</Badge>
            <h1 className="mt-7 max-w-3xl text-5xl font-semibold leading-[1.02] tracking-[-0.055em] sm:text-6xl lg:text-7xl">Investir dans le monde, <span className="bg-gradient-to-r from-[#e6b84d] via-[#f4d47e] to-[#20c9a5] bg-clip-text text-transparent">depuis la RDC.</span></h1>
            <p className="mt-6 max-w-xl text-base leading-8 text-slate-300 sm:text-lg">AFRICOIN TRADING GROUP réunit digital assets, trading, FinTech et blockchain dans une infrastructure financière numérique panafricaine, pensée depuis Goma pour les investisseurs de la région.</p>
            <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button asChild className="h-12 bg-[#e6b84d] px-6 font-semibold text-[#08131f] shadow-[0_12px_35px_rgba(230,184,77,.2)] transition hover:-translate-y-0.5 hover:bg-[#f3d27a]"><Link href="/inscription">Créer mon compte <ArrowRight className="ml-2 h-4 w-4" /></Link></Button><Button asChild variant="outline" className="h-12 border-white/20 bg-white/[0.04] px-6 text-white transition hover:-translate-y-0.5 hover:bg-white/10 hover:text-white"><a href="#marches">Découvrir la plateforme <ChevronRight className="ml-2 h-4 w-4" /></a></Button></div>
            <div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-xs text-slate-400"><span className="flex items-center gap-2"><LockKeyhole className="h-4 w-4 text-[#20c9a5]" />Session protégée</span><span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-[#e6b84d]" />KYC / AML-CFT intégré</span><span className="flex items-center gap-2"><Globe2 className="h-4 w-4 text-[#73d2de]" />CDF & USD</span></div>
          </div>
          <div className="relative mx-auto w-full max-w-[500px] lg:translate-y-4"><div className="absolute -inset-10 rounded-full bg-[#20c9a5]/10 blur-3xl motion-safe:animate-pulse" /><div className="relative rounded-[30px] border border-white/15 bg-white/[0.07] p-3 shadow-2xl backdrop-blur-xl transition duration-300 hover:-translate-y-1 hover:border-[#20c9a5]/40 sm:p-4"><div className="rounded-[22px] bg-[#f7faf5] p-5 text-[#0b1f2a] sm:p-6"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><img src={logo} alt="AFRICOIN TRADING GROUP" className="h-10 w-10 rounded-xl object-cover" /><div><p className="text-sm font-semibold">Vue d’ensemble</p><p className="text-xs text-slate-500">Compte sécurisé</p></div></div><span className="rounded-full bg-[#e8f5f0] px-2.5 py-1 text-[10px] font-semibold text-[#008f76]">ACTIF</span></div><div className="mt-7 rounded-2xl bg-[#0b1f2a] p-5 text-white"><div className="flex items-center justify-between text-xs text-slate-400"><span>Portefeuille consolidé</span><span>CDF / USD</span></div><p className="mt-4 text-4xl font-semibold tracking-tight">0,00 $US</p><p className="mt-2 text-xs text-slate-400">Une base claire pour suivre vos décisions.</p><div className="mt-6 h-2 rounded-full bg-white/10"><div className="h-full w-[72%] rounded-full bg-gradient-to-r from-[#e6b84d] to-[#20c9a5]" /></div><div className="mt-2 flex justify-between text-[10px] text-slate-500"><span>Liquidités</span><span>Prêt pour votre parcours</span></div></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-[#eef8d8] p-4 transition hover:-translate-y-0.5"><WalletCards className="h-4 w-4 text-[#698b2d]" /><p className="mt-4 text-xs text-slate-500">Liquidités USD</p><p className="mt-1 text-lg font-semibold">0,00 $US</p></div><div className="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-100 transition hover:-translate-y-0.5"><BarChart3 className="h-4 w-4 text-[#008f76]" /><p className="mt-4 text-xs text-slate-500">Marchés suivis</p><p className="mt-1 text-lg font-semibold">Actions · FX</p></div></div></div></div><div className="absolute -bottom-5 -left-5 hidden rounded-2xl border border-white/10 bg-[#0b1f2a]/90 px-4 py-3 text-xs shadow-xl backdrop-blur sm:block"><span className="mr-2 inline-block h-2 w-2 rounded-full bg-[#20c9a5]" />Catalogue partenaire en attente</div></div>
        </div>
      </section>

      <section className="border-b border-slate-200 bg-white py-10"><div className="mx-auto grid max-w-7xl gap-6 px-5 sm:px-8 md:grid-cols-[1.2fr_.8fr] md:items-center"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#698b2d]">AFRICOIN TRADING GROUP · ATG</p><h2 className="mt-3 text-2xl font-semibold tracking-tight text-[#0b1f2a]">Les marchés numériques d’Afrique.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-500">Nom commercial : <strong>AFRICOIN TRADING</strong> · Siège initial proposé : Goma, RDC. Une infrastructure financière numérique panafricaine dans les secteurs des digital assets, du trading, de la FinTech et de la blockchain.</p></div><div className="rounded-2xl bg-[#edf5e8] p-5 text-sm text-[#365d4d]"><p className="font-semibold">Notre cap</p><p className="mt-2 leading-6">Construire une infrastructure financière numérique panafricaine.</p><p className="mt-3 text-xs font-medium text-[#698b2d]">Alternative : « Échangez avec l’Afrique. Connectez l’Afrique. »</p></div></div></section>

      <section id="marches" className="relative mx-auto max-w-7xl scroll-mt-8 px-5 py-20 sm:px-8 sm:py-28"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#698b2d]">Une seule vue, plusieurs marchés</p><h2 className="mt-4 text-3xl font-semibold tracking-tight text-[#0b1f2a] sm:text-4xl">Une plateforme conçue pour décider avec plus de clarté.</h2><p className="mt-4 text-base leading-7 text-slate-500">Explorez les grands repères d’un parcours d’investissement avant de vous connecter. Chaque choix révèle son contexte, ses limites et son niveau d’information.</p></div><Link href="/tarifs-risques-conditions" className="inline-flex items-center text-sm font-semibold text-[#006b5c] transition hover:gap-2">Voir tarifs & risques <ArrowRight className="ml-2 h-4 w-4" /></Link></div>
        <div className="mt-12 grid gap-5 lg:grid-cols-[.85fr_1.15fr]">
          <div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-1">{marketSignals.map(signal => { const Icon = signal.icon; const active = signal.id === activeMarket; return <button key={signal.id} onClick={() => setActiveMarket(signal.id)} className={`group rounded-[22px] border p-5 text-left transition duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#20c9a5] ${active ? "border-[#0b1f2a] bg-[#0b1f2a] text-white shadow-[0_16px_40px_rgba(11,31,42,.15)]" : "border-slate-200 bg-white hover:-translate-y-0.5 hover:border-[#a7d8cb] hover:shadow-[0_14px_35px_rgba(11,31,42,.07)]"}`}><div className="flex items-center justify-between"><span className={`grid h-10 w-10 place-items-center rounded-xl ${active ? "bg-white/10 text-[#e6b84d]" : "bg-[#e8f5f0] text-[#008f76]"}`}><Icon className="h-5 w-5" /></span><ChevronRight className={`h-4 w-4 transition-transform ${active ? "translate-x-1 text-[#e6b84d]" : "text-slate-300 group-hover:translate-x-1"}`} /></div><p className={`mt-5 text-[10px] font-semibold uppercase tracking-[0.18em] ${active ? "text-[#20c9a5]" : "text-[#698b2d]"}`}>{signal.eyebrow}</p><h3 className={`mt-2 font-semibold ${active ? "text-white" : "text-[#0b1f2a]"}`}>{signal.label}</h3></button>; })}</div>
          <div className="relative overflow-hidden rounded-[28px] bg-[#edf5e8] p-7 sm:p-9"><div className="absolute -right-12 -top-16 h-48 w-48 rounded-full bg-[#20c9a5]/20 blur-2xl" /><div className="relative"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#698b2d]">Aperçu de marché</p><h3 className="mt-4 max-w-md text-2xl font-semibold tracking-tight text-[#0b1f2a] sm:text-3xl">{activeSignal.title}</h3></div><span className="grid h-12 w-12 place-items-center rounded-2xl bg-white text-[#008f76] shadow-sm"><ActiveIcon className="h-5 w-5" /></span></div><p className="mt-5 max-w-lg text-sm leading-7 text-slate-600">{activeSignal.text}</p><div className="mt-9 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-white/80 p-4"><p className="text-[10px] uppercase tracking-[0.16em] text-slate-400">Contexte</p><p className="mt-2 text-sm font-semibold text-[#0b1f2a]">Visible avant l’action</p></div><div className="rounded-2xl bg-white/80 p-4"><p className="text-[10px] uppercase tracking-[0.16em] text-slate-400">Exécution</p><p className="mt-2 text-sm font-semibold text-[#0b1f2a]">Partenaire requis</p></div><div className="rounded-2xl bg-white/80 p-4"><p className="text-[10px] uppercase tracking-[0.16em] text-slate-400">Devise</p><p className="mt-2 text-sm font-semibold text-[#0b1f2a]">Selon instrument</p></div></div><div className="mt-8 flex items-center gap-2 text-xs font-medium text-[#006b5c]"><Check className="h-4 w-4" />Aucune promesse de rendement ou d’exécution automatique</div></div></div>
        </div>
      </section>

      <section id="securite" className="bg-[#edf5e8] py-20 sm:py-28"><div className="mx-auto grid max-w-7xl gap-12 px-5 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#698b2d]">La confiance avant la vitesse</p><h2 className="mt-4 text-3xl font-semibold tracking-tight text-[#0b1f2a] sm:text-4xl">Des garde-fous intégrés à chaque étape.</h2><p className="mt-5 text-base leading-7 text-slate-600">Les fonctionnalités sensibles sont accompagnées de contrôles KYC/AML-CFT, de journaux d’audit et de validations adaptées. Les opérations réelles restent conditionnées aux autorisations et partenaires agréés requis.</p><Button asChild className="mt-8 bg-[#0b1f2a] text-white shadow-lg transition hover:-translate-y-0.5 hover:bg-[#163747]"><Link href="/inscription">Voir mon parcours sécurisé <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div><div className="grid gap-4 sm:grid-cols-2"><Trust title="Identité vérifiée" text="Un parcours KYC structuré et lisible pour connaître les prochaines étapes." /><Trust title="Traçabilité financière" text="Demandes, décisions, références et réconciliations restent journalisées." /><Trust title="Accès par rôle" text="Client, conformité et administration disposent d’espaces distincts." /><Trust title="Activation progressive" text="Les connexions partenaires et autorisations précèdent toute exécution réelle." /></div></div></section>

      <section id="parcours" className="mx-auto max-w-7xl scroll-mt-8 px-5 py-20 sm:px-8 sm:py-28"><div className="text-center"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#698b2d]">Votre parcours</p><h2 className="mt-4 text-3xl font-semibold tracking-tight text-[#0b1f2a] sm:text-4xl">Commencer simplement. Évoluer proprement.</h2></div><div className="relative mt-14 grid gap-8 md:grid-cols-3"><Step number="01" title="Créer votre espace" text="Connectez-vous et complétez votre profil investisseur." /><Step number="02" title="Comprendre les marchés" text="Explorez les instruments, le risque et les règles de chaque marché." /><Step number="03" title="Préparer vos décisions" text="Suivez vos liquidités, votre conformité et vos demandes avec visibilité." /></div></section>

      <section id="faq" className="border-t border-slate-200 bg-white py-20 scroll-mt-8"><div className="mx-auto grid max-w-7xl gap-12 px-5 sm:px-8 lg:grid-cols-[.72fr_1.28fr] lg:items-start"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#698b2d]">Questions fréquentes</p><h2 className="mt-4 text-3xl font-semibold tracking-tight text-[#0b1f2a] sm:text-4xl">Comprendre avant de commencer.</h2><p className="mt-4 max-w-md text-sm leading-7 text-slate-500">Nous préférons une information claire à une promesse rapide. Consultez les réponses essentielles ou lisez la page complète dédiée aux tarifs, risques et conditions.</p><Link href="/tarifs-risques-conditions" className="mt-6 inline-flex items-center text-sm font-semibold text-[#006b5c] hover:underline">Lire les conditions essentielles <ArrowRight className="ml-2 h-4 w-4" /></Link></div><div className="space-y-3">{faqs.map(([question, answer], index) => { const open = openFaq === index; return <div key={question} className={`overflow-hidden rounded-2xl border transition ${open ? "border-[#a7d8cb] bg-[#f5faf5]" : "border-slate-200 bg-white"}`}><button className="flex w-full items-center justify-between gap-4 p-5 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-[#20c9a5]" onClick={() => setOpenFaq(open ? null : index)} aria-expanded={open}><span className="text-sm font-semibold text-[#0b1f2a]">{question}</span><ChevronDown className={`h-4 w-4 shrink-0 text-[#698b2d] transition-transform duration-200 ${open ? "rotate-180" : ""}`} /></button>{open && <div className="px-5 pb-5 text-sm leading-7 text-slate-600">{answer}</div>}</div>; })}</div></div></section>

      <section className="border-t border-slate-200 bg-[#f8faf7] py-16"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-5 sm:px-8 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#698b2d]">Prêt à commencer ?</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-[#0b1f2a]">Investir avec une information plus claire.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-slate-500">AFRICOIN TRADING GROUP vous accompagne dans un parcours progressif. L’accès aux fonctions réelles dépend des validations réglementaires et partenaires applicables.</p></div><Button asChild className="h-12 shrink-0 bg-[#0b1f2a] px-6 text-white shadow-lg transition hover:-translate-y-0.5 hover:bg-[#163747]"><Link href="/inscription">Accéder à la plateforme <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div></section>
    </main>
    <footer className="bg-[#061526] py-8 text-slate-400"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 text-xs sm:px-8 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-3"><img src={favicon} alt="" className="h-8 w-8 rounded-lg" /><span>© 2026 AFRICOIN TRADING GROUP · Les marchés numériques d’Afrique</span></div><div className="flex gap-5"><Link href="/tarifs-risques-conditions" className="hover:text-white">Tarifs & risques</Link><Link href="/documents" className="hover:text-white">Documents</Link><Link href="/documents" className="hover:text-white">Confidentialité</Link><Link href="/documents" className="hover:text-white">Réclamations</Link></div></div></footer>
  </div>;
}

function Trust({ title, text }: { title: string; text: string }) { return <div className="rounded-[22px] bg-white p-5 shadow-sm transition duration-200 hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#e8f5f0] text-[#008f76]"><Check className="h-4 w-4" /></span><h3 className="font-semibold text-[#0b1f2a]">{title}</h3></div><p className="mt-3 text-sm leading-6 text-slate-500">{text}</p></div>; }
function Step({ number, title, text }: { number: string; title: string; text: string }) { return <div className="relative rounded-[24px] border border-slate-200 bg-white p-6 shadow-sm transition duration-200 hover:-translate-y-1 hover:shadow-lg"><span className="text-sm font-semibold tracking-[0.18em] text-[#e0ae3e]">{number}</span><h3 className="mt-5 text-lg font-semibold text-[#0b1f2a]">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p><Sparkles className="absolute right-6 top-6 h-5 w-5 text-[#20c9a5]" /></div>; }
