import { useMemo, useState } from "react";
import { useMarketStream } from "@/hooks/useMarketStream";
import { MarketStreamStatus } from "@/components/MarketStreamStatus";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { ArrowDownRight, ArrowUpRight, CandlestickChart, Info, Search, ShieldAlert, Star, TrendingDown, TrendingUp } from "lucide-react";
import { toast } from "sonner";

export default function Market() {
  const [query, setQuery] = useState("");
  const [assetClass, setAssetClass] = useState<"all" | "equity" | "fx_spot">("all");
  const [selected, setSelected] = useState<any>(null);
  const [side, setSide] = useState<"buy" | "sell">("buy");
  const [quantity, setQuantity] = useState("1");
  const marketStream = useMarketStream();
  const { data: instruments = [], isLoading } = trpc.market.catalog.useQuery({ query, assetClass }, { refetchInterval: marketStream.isFallback ? 5000 : 30000 });
  const displayInstruments = useMemo(() => instruments.map(instrument => ({ ...instrument, ...(marketStream.quotes[instrument.symbol] ?? {}) })), [instruments, marketStream.quotes]);
  const { data: watchlist = [] } = trpc.watchlist.list.useQuery();
  const { data: dashboard } = trpc.dashboard.summary.useQuery();
  const utils = trpc.useUtils();
  const addWatch = trpc.watchlist.add.useMutation({ onSuccess: () => void utils.watchlist.list.invalidate() });
  const removeWatch = trpc.watchlist.remove.useMutation({ onSuccess: () => void utils.watchlist.list.invalidate() });
  const order = trpc.orders.placeSpot.useMutation({ onSuccess: result => { toast.success(result.message); setSelected(null); }, onError: error => toast.error(error.message) });
  const selectedPrice = Number(marketStream.quotes[selected?.symbol ?? ""]?.price ?? selected?.price ?? 0);
  const notional = useMemo(() => selectedPrice * Number(quantity || 0), [selectedPrice, quantity]);
  const selectedWallet = dashboard?.wallets?.find(wallet => wallet.currency === selected?.quoteCurrency);
  const tradeBlockedReason = dashboard?.kyc?.status !== "approved" ? "Votre compte doit être approuvé par la conformité avant toute opération." : Number(selectedWallet?.availableBalance ?? 0) < notional ? `Solde disponible insuffisant (${selectedWallet?.availableBalance ?? "0"} ${selected?.quoteCurrency ?? "USD"}).` : "";

  return <div className="min-h-screen bg-[#f5f7f5] px-4 py-6 sm:px-8 lg:px-10"><div className="mx-auto max-w-[1500px]">
    <header className="flex flex-col gap-4 border-b border-slate-200 pb-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#6b8e23]">Marchés</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-[#0b1f2a]">Actions & forex spot</h1><p className="mt-2 max-w-xl text-sm leading-6 text-slate-500">Explorez les instruments disponibles, les niveaux de risque et les cours disponibles. L’effet de levier et les CFD sont désactivés.</p></div><MarketStreamStatus connection={marketStream.connection} providerState={marketStream.providerState} message={marketStream.providerMessage} lastUpdate={marketStream.lastUpdate} /></header>
    <div className="mt-6 grid gap-5 xl:grid-cols-[1fr_310px]"><section><div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="Rechercher un symbole ou instrument" className="h-11 rounded-xl border-slate-200 bg-white pl-9" /></div><div className="flex rounded-xl border border-slate-200 bg-white p-1"><FilterButton active={assetClass === "all"} onClick={() => setAssetClass("all")}>Tous</FilterButton><FilterButton active={assetClass === "equity"} onClick={() => setAssetClass("equity")}>Actions</FilterButton><FilterButton active={assetClass === "fx_spot"} onClick={() => setAssetClass("fx_spot")}>Forex spot</FilterButton></div></div><div className="mt-4 overflow-hidden rounded-[24px] border border-slate-200 bg-white shadow-sm"><div className="hidden grid-cols-[1.5fr_.8fr_.8fr_.7fr_110px] gap-4 border-b border-slate-100 px-5 py-3 text-[10px] font-semibold uppercase tracking-[0.15em] text-slate-400 sm:grid"><span>Instrument</span><span>Classe</span><span>Cours</span><span>Variation</span><span /></div>{isLoading ? <div className="p-8 text-sm text-slate-500">Chargement des instruments…</div> : displayInstruments.map(instrument => <InstrumentRow key={instrument.id} instrument={instrument} isWatched={watchlist.some(item => item.instrumentId === instrument.id)} onToggle={() => watchlist.some(item => item.instrumentId === instrument.id) ? removeWatch.mutate({ instrumentId: Number(instrument.id) }) : addWatch.mutate({ instrumentId: Number(instrument.id) })} onTrade={(nextSide: "buy" | "sell") => { setSide(nextSide); setSelected(instrument); }} />)}{!isLoading && !instruments.length && <div className="p-8 text-center text-sm text-slate-500">Aucun instrument ne correspond à votre recherche.</div>}</div></section>
      <aside className="space-y-5"><Card className="rounded-[24px] border-0 bg-[#0b1f2a] text-white shadow-[0_18px_60px_rgba(11,31,42,.13)]"><CardHeader><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#20c9a5]">Protection</p><CardTitle className="mt-2 text-lg font-medium">Règles de marché</CardTitle></div><CandlestickChart className="h-5 w-5 text-[#e6b84d]" /></div></CardHeader><CardContent className="space-y-4 text-sm leading-6 text-slate-300"><Rule title="Spot uniquement" text="Les ordres proposés ici sont sans marge et sans effet de levier." /><Rule title="Exécution soumise à validation" text="Aucun ordre réel n’est transmis tant qu’un courtier agréé et ses credentials ne sont pas connectés." /><Rule title="Risque visible" text="Chaque instrument affiche une classification de risque avant l’action." /></CardContent></Card><Card className="rounded-[24px] border-slate-200 bg-white"><CardHeader><CardTitle className="text-base text-[#0b1f2a]">Votre watchlist</CardTitle></CardHeader><CardContent><div className="flex items-start gap-3 rounded-2xl bg-[#f5f8f2] p-4"><Star className="mt-0.5 h-4 w-4 text-[#9ab957]" /><p className="text-xs leading-5 text-slate-500">Ajoutez vos instruments favoris depuis le catalogue. La synchronisation de watchlist est prête pour le prochain branchement partenaire.</p></div></CardContent></Card></aside>
    </div>
    <Dialog open={Boolean(selected)} onOpenChange={open => !open && setSelected(null)}><DialogContent className="rounded-[24px] border-slate-200 bg-white text-[#0b1f2a] shadow-[0_24px_80px_rgba(6,21,38,.28)] sm:max-w-md"><DialogHeader><DialogTitle className="text-[#0b1f2a]">Passer un ordre spot</DialogTitle><DialogDescription>{selected?.symbol} · {selected?.name}</DialogDescription></DialogHeader><div className="rounded-2xl bg-[#f5f8f2] p-4"><div className="flex items-center justify-between"><span className="text-sm text-slate-500">Cours indicatif</span><span className="font-semibold text-[#0b1f2a]">{selectedPrice.toFixed(selected?.assetClass === "fx_spot" ? 4 : 2)} {selected?.quoteCurrency}</span></div><div className="mt-3 flex items-center justify-between"><span className="text-sm text-slate-500">Risque</span><Badge className="bg-[#fff2d9] text-[#94681f]">{selected?.riskLevel}</Badge></div></div><div className="grid grid-cols-2 gap-2"><Button onClick={() => setSide("buy")} className={side === "buy" ? "bg-[#4d8d73] text-white" : "bg-slate-100 text-slate-600 hover:bg-slate-200"}>Acheter</Button><Button onClick={() => setSide("sell")} className={side === "sell" ? "bg-[#bb6e6e] text-white" : "bg-slate-100 text-slate-600 hover:bg-slate-200"}>Vendre</Button></div><div><label className="text-xs font-medium text-slate-600">Quantité</label><Input type="number" min="0.0001" step="0.0001" value={quantity} onChange={event => setQuantity(event.target.value)} className="mt-2" /></div><div className="flex items-center justify-between border-t border-slate-100 pt-3 text-sm"><span className="text-slate-500">Valeur indicative</span><span className="font-semibold text-[#0b1f2a]">{notional.toFixed(2)} {selected?.quoteCurrency}</span></div><p className="text-xs leading-5 text-slate-500"><Info className="mr-1 inline h-3.5 w-3.5" />Cet ordre sera enregistré et transmis uniquement après connexion du courtier agréé. Aucun fonds ne sera engagé avant validation.</p>{tradeBlockedReason && <p className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs leading-5 text-amber-800">{tradeBlockedReason}</p>}<DialogFooter><Button disabled={order.isPending || Boolean(tradeBlockedReason)} onClick={() => order.mutate({ instrumentId: Number(selected.id), symbol: selected.symbol, side, orderType: "market", quantity: Number(quantity), idempotencyKey: crypto.randomUUID() })} className="w-full bg-[#0b1f2a] text-white hover:bg-[#163747]">{order.isPending ? "Validation…" : tradeBlockedReason ? "Trading indisponible" : `Confirmer ${side === "buy" ? "l’achat" : "la vente"}`}</Button></DialogFooter></DialogContent></Dialog>
  </div></div>;
}
function FilterButton({ active, onClick, children }: { active: boolean; onClick: () => void; children: React.ReactNode }) { return <button onClick={onClick} className={`rounded-lg px-3 py-2 text-xs font-medium transition ${active ? "bg-[#0b1f2a] text-white" : "text-slate-500 hover:bg-slate-100"}`}>{children}</button>; }
function InstrumentRow({ instrument, isWatched, onToggle, onTrade }: { instrument: any; isWatched: boolean; onToggle: () => void; onTrade: (side: "buy" | "sell") => void }) { const positive = Number(instrument.changePercent) >= 0; return <div className="grid gap-3 border-b border-slate-100 px-5 py-4 last:border-0 sm:grid-cols-[1.5fr_.8fr_.8fr_.7fr_110px] sm:items-center"><div><div className="flex items-center gap-2"><span className="font-semibold text-[#0b1f2a]">{instrument.symbol}</span><Badge variant="outline" className="text-[10px]">{instrument.exchange}</Badge></div><p className="mt-1 text-xs text-slate-500">{instrument.name}</p></div><span className="text-xs text-slate-500">{instrument.assetClass === "equity" ? "Action" : "Forex spot"}</span><span className="font-medium text-[#0b1f2a]">{instrument.price} <span className="text-xs text-slate-400">{instrument.quoteCurrency}</span></span><span className={`flex items-center gap-1 text-sm font-medium ${positive ? "text-[#4d8d73]" : "text-[#bb6e6e]"}`}>{positive ? <TrendingUp className="h-3.5 w-3.5" /> : <TrendingDown className="h-3.5 w-3.5" />}{positive ? "+" : ""}{instrument.changePercent}%</span><div className="flex items-center gap-2"><button onClick={onToggle} aria-label={isWatched ? "Retirer de la watchlist" : "Ajouter à la watchlist"} className={`grid h-8 w-8 place-items-center rounded-lg border ${isWatched ? "border-[#b9d77a] bg-[#e8f5f0] text-[#008f76]" : "border-slate-200 text-slate-400"}`}><Star className={`h-3.5 w-3.5 ${isWatched ? "fill-current" : ""}`} /></button><Button size="sm" onClick={() => onTrade("buy")} className="h-8 bg-[#0b1f2a] px-3 text-xs text-white hover:bg-[#163747]">Trade</Button></div></div>; }
function Rule({ title, text }: { title: string; text: string }) { return <div className="border-b border-white/10 pb-3 last:border-0 last:pb-0"><p className="font-medium text-white">{title}</p><p className="mt-1 text-xs text-slate-400">{text}</p></div>; }
