import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ArrowLeft, ArrowRight, Check, ChevronDown, FileText, Info, LockKeyhole, ShieldAlert, WalletCards } from "lucide-react";
import { Link } from "wouter";

const favicon = "/assets/branding/logoafricoin.jpeg";

const pricingRows = [
  { title: "Accès à la plateforme", value: "Aucun abonnement public annoncé", note: "Les conditions définitives seront communiquées avant toute activation commerciale." },
  { title: "Dépôts et retraits", value: "Frais éventuels du partenaire", note: "Le canal sélectionné, ses frais et le montant net sont présentés avant confirmation." },
  { title: "Conversion de devises", value: "Spread ou frais du partenaire", note: "Le taux, la devise et les frais applicables sont affichés avant validation." },
  { title: "Ordres actions et forex spot", value: "Commission et frais de marché à confirmer", note: "Tout coût sera affiché avant transmission à un courtier ou fournisseur agréé." },
  { title: "Conservation et tenue de compte", value: "Conditions dépendantes du partenaire", note: "Les frais éventuels ne s’appliquent qu’après information et acceptation des conditions." },
];

const risks = [
  { title: "Risque de perte en capital", text: "La valeur d’un instrument peut baisser. Vous pouvez perdre une partie ou la totalité du capital investi. N’investissez que des sommes dont la perte est supportable." },
  { title: "Volatilité des marchés", text: "Les actions et les devises peuvent évoluer rapidement sous l’effet des marchés, des nouvelles économiques, de la liquidité ou des horaires de cotation." },
  { title: "Risque de change", text: "Une variation du taux de change peut modifier la valeur d’un investissement ou d’un solde exprimé dans une autre devise, notamment entre CDF et USD." },
  { title: "Risque de liquidité et de contrepartie", text: "Un ordre peut être retardé, partiellement exécuté ou impossible à exécuter. Les opérations dépendent des marchés et des partenaires agréés connectés." },
  { title: "Risque opérationnel et cyber", text: "Une interruption, une erreur technique ou un incident de sécurité peut affecter l’accès ou le traitement. Des contrôles, journaux et procédures de reprise sont prévus." },
  { title: "Pas de marge ni de CFD par défaut", text: "Le levier, la marge et les CFD ne font pas partie du parcours actuel. Toute évolution future nécessitera des autorisations, des documents et une validation distincte." },
];

const terms = [
  { title: "Accès et vérification d’identité", text: "L’accès aux espaces et aux fonctions financières est soumis à l’authentification, à la fourniture d’informations exactes et aux contrôles KYC/AML-CFT applicables. Une vérification complémentaire peut être demandée." },
  { title: "Ordres et information de marché", text: "Les instruments, cours, risques et statuts affichés servent à informer et à préparer une décision. Un ordre n’est pas une garantie d’exécution. Tant que les partenaires requis ne sont pas activés, la demande reste dans un état non final." },
  { title: "Dépôts, retraits et fonds", text: "Toute demande de financement est enregistrée, contrôlée et peut être soumise à une revue conformité. Un dépôt ou un retrait n’est pas considéré comme exécuté avant confirmation du canal agréé et rapprochement des données." },
  { title: "Suspension et limites", text: "AFRICOIN TRADING GROUP peut limiter, suspendre ou différer une action pour des raisons de sécurité, de conformité, de disponibilité du partenaire ou de cohérence des données. Les raisons pertinentes sont conservées dans l’historique." },
  { title: "Documents et acceptation", text: "Avant l’accès aux fonctions concernées, les documents obligatoires — risques, tarification, conditions, confidentialité et réclamations — doivent être consultés et, lorsque requis, acceptés dans leur version publiée." },
  { title: "Réclamations et données personnelles", text: "Les demandes peuvent être adressées par le canal de réclamation prévu. Les données sont traitées selon la politique de confidentialité et les obligations applicables, avec des mesures d’accès et de traçabilité." },
];

export default function PricingRisksTerms() {
  return <div className="min-h-screen bg-[#f7faf6] text-[#0b1f2a]">
    <header className="border-b border-white/10 bg-[#061526] text-white"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8"><Link href="/" className="flex items-center gap-3" aria-label="Retour à l’accueil AFRICOIN TRADING GROUP"><img src={favicon} alt="" className="h-10 w-10 rounded-xl border border-[#d9aa3f]/50" /><span><span className="block text-sm font-semibold">AFRICOIN <span className="text-[#e6b84d]">TRADING GROUP</span></span><span className="block text-[9px] uppercase tracking-[0.22em] text-[#20c9a5]">Les marchés numériques d’Afrique</span></span></Link><div className="flex items-center gap-3"><Link href="/" className="hidden items-center gap-2 text-sm text-slate-300 hover:text-white sm:flex"><ArrowLeft className="h-4 w-4" />Accueil</Link><Button asChild className="bg-[#e6b84d] text-[#08131f] hover:bg-[#f3d27a]"><Link href="/connexion">Se connecter <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div></div></header>
    <main>
      <section className="bg-[#061526] pb-16 pt-12 text-white sm:pb-20 sm:pt-16"><div className="mx-auto max-w-7xl px-5 sm:px-8"><Badge className="border-[#20c9a5]/30 bg-[#20c9a5]/10 text-[#86efd7]"><Info className="mr-2 h-3.5 w-3.5" />Information à consulter avant connexion</Badge><div className="mt-7 grid gap-10 lg:grid-cols-[1fr_.75fr] lg:items-end"><div><h1 className="max-w-3xl text-4xl font-semibold leading-tight tracking-[-0.04em] sm:text-6xl">Tarifs, risques & <span className="text-[#e6b84d]">conditions.</span></h1><p className="mt-5 max-w-2xl text-base leading-8 text-slate-300 sm:text-lg">Une synthèse claire de ce que vous devez comprendre avant d’utiliser AFRICOIN TRADING GROUP. Les informations contractuelles complètes sont publiées dans l’espace Documents et doivent être acceptées lorsqu’elles s’appliquent.</p></div><div className="rounded-[24px] border border-white/10 bg-white/[0.06] p-5"><div className="flex items-start gap-3"><LockKeyhole className="mt-1 h-5 w-5 text-[#20c9a5]" /><div><p className="font-semibold">Une décision informée d’abord</p><p className="mt-2 text-sm leading-6 text-slate-400">Les frais et les risques sont présentés avant toute demande ou transmission. Les flux réels restent soumis aux validations réglementaires et partenaires applicables.</p></div></div></div></div></div></section>

      <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-24"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#698b2d]">01 · Tarification</p><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">Des coûts lisibles, sans frais inventés.</h2><p className="mt-4 text-base leading-7 text-slate-500">Les montants dépendant des canaux, des marchés et des partenaires ne sont pas présentés comme des prix fixes. Toute tarification applicable doit être affichée avant votre confirmation.</p></div><div className="mt-10 overflow-hidden rounded-[24px] border border-slate-200 bg-white shadow-sm"><div className="hidden grid-cols-[.9fr_1fr_1.4fr] gap-5 border-b border-slate-100 bg-[#fbfcfa] px-6 py-4 text-[10px] font-semibold uppercase tracking-[0.16em] text-slate-400 sm:grid"><span>Poste</span><span>Principe</span><span>Quand l’information apparaît</span></div>{pricingRows.map(row => <div key={row.title} className="grid gap-2 border-b border-slate-100 px-5 py-5 last:border-0 sm:grid-cols-[.9fr_1fr_1.4fr] sm:gap-5 sm:px-6"><div className="font-semibold text-[#0b1f2a]">{row.title}</div><div className="text-sm font-medium text-[#008f76]">{row.value}</div><div className="text-sm leading-6 text-slate-500">{row.note}</div></div>)}</div><div className="mt-5 flex items-start gap-3 rounded-2xl border border-[#b8d9cd] bg-[#e8f5f0] p-4 text-sm leading-6 text-[#006b5c]"><Check className="mt-0.5 h-4 w-4 shrink-0" /><p><strong>Engagement de clarté :</strong> aucun coût dépendant d’un partenaire ne doit être présenté comme certain avant son affichage, sa compréhension et votre confirmation.</p></div></section>

      <section className="bg-[#edf5e8] py-16 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#698b2d]">02 · Risques</p><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">Comprendre ce qui peut mal évoluer.</h2><p className="mt-4 text-base leading-7 text-slate-600">Investir comporte des risques. Cette page ne constitue pas un conseil personnalisé et ne remplace pas l’évaluation de votre situation, de votre horizon ou de votre tolérance au risque.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{risks.map((risk, index) => <article key={risk.title} className="rounded-[22px] bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#fff2d9] text-[#94681f]"><ShieldAlert className="h-4 w-4" /></span><span className="text-[10px] font-semibold uppercase tracking-[0.16em] text-slate-400">Risque {String(index + 1).padStart(2, "0")}</span></div><h3 className="mt-5 text-base font-semibold text-[#0b1f2a]">{risk.title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{risk.text}</p></article>)}</div></div></section>

      <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-24"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr] lg:items-start"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#698b2d]">03 · Conditions</p><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">Les règles du parcours, en langage clair.</h2><p className="mt-4 text-base leading-7 text-slate-500">Ce résumé vous aide à vous orienter. Les conditions complètes, les versions et les preuves d’acceptation sont disponibles dans les documents publiés de la plateforme.</p><div className="mt-7 rounded-[22px] bg-[#0b1f2a] p-5 text-white"><div className="flex items-start gap-3"><FileText className="mt-1 h-5 w-5 text-[#e6b84d]" /><div><p className="font-semibold">Documents complets</p><p className="mt-2 text-sm leading-6 text-slate-400">Après connexion, retrouvez les versions applicables et votre état d’acceptation dans Documents.</p><Button asChild variant="outline" className="mt-4 border-white/20 bg-white/[0.04] text-white hover:bg-white/10 hover:text-white"><Link href="/documents">Voir l’espace Documents <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div></div></div></div><div className="space-y-3">{terms.map(term => <details key={term.title} className="group rounded-[20px] border border-slate-200 bg-white p-5 shadow-sm"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-semibold text-[#0b1f2a]"><span>{term.title}</span><ChevronDown className="h-4 w-4 shrink-0 text-[#698b2d] transition group-open:rotate-180" /></summary><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-500">{term.text}</p></details>)}</div></div></section>

      <section className="border-t border-slate-200 bg-white py-14"><div className="mx-auto flex max-w-7xl flex-col gap-7 px-5 sm:px-8 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#698b2d]">Étape suivante</p><h2 className="mt-3 text-2xl font-semibold tracking-tight text-[#0b1f2a]">Vous avez compris les bases ?</h2><p className="mt-2 max-w-xl text-sm leading-6 text-slate-500">Connectez-vous pour compléter votre profil, lire les documents publiés et voir les fonctions disponibles pour votre compte.</p></div><Button asChild className="h-12 shrink-0 bg-[#e6b84d] px-6 font-semibold text-[#08131f] hover:bg-[#f3d27a]"><Link href="/connexion">Accéder à mon espace <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div></section>
    </main>
    <footer className="bg-[#061526] py-8 text-slate-400"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 text-xs sm:px-8 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-3"><img src={favicon} alt="" className="h-8 w-8 rounded-lg" /><span>© 2026 AFRICOIN TRADING GROUP · Information avant connexion</span></div><div className="flex gap-5"><Link href="/" className="hover:text-white">Accueil</Link><Link href="/documents" className="hover:text-white">Documents complets</Link><Link href="/connexion" className="hover:text-white">Se connecter</Link></div></div></footer>
  </div>;
}
