import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { ArrowDownLeft, ArrowUpRight, Banknote, ChevronRight, Clock3, LockKeyhole, ShieldCheck, WalletCards } from "lucide-react";
import { toast } from "sonner";

export default function Wallets() {
  const [dialog, setDialog] = useState<"deposit" | "withdrawal" | null>(null);
  const [currency, setCurrency] = useState<"USD" | "CDF">("USD");
  const [amount, setAmount] = useState("");
  const { data: wallets = [] } = trpc.wallets.balances.useQuery();
  const { data: requests } = trpc.portfolio.requests.useQuery();
  const deposit = trpc.wallets.requestDeposit.useMutation({ onSuccess: result => { toast.success(result.message); setDialog(null); setAmount(""); }, onError: error => toast.error(error.message) });
  const withdrawal = trpc.wallets.requestWithdrawal.useMutation({ onSuccess: result => { toast.success(result.message); setDialog(null); setAmount(""); }, onError: error => toast.error(error.message) });
  const walletFor = (code: string) => wallets.find(wallet => wallet.currency === code) ?? { availableBalance: "0.00", pendingBalance: "0.00", currency: code };

  return <div className="min-h-screen bg-[#f7f7f2] px-4 py-6 sm:px-8 lg:px-10"><div className="mx-auto max-w-[1500px]">
    <header className="flex flex-col gap-4 border-b border-slate-200 pb-6 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#087f78]">Portefeuille</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-[#0a2233]">Vos liquidités, séparées par devise</h1><p className="mt-2 text-sm leading-6 text-slate-500">Les demandes restent sous contrôle conformité jusqu’à la connexion d’un partenaire de paiement agréé.</p></div><div className="flex items-center gap-2 rounded-2xl border border-slate-200 bg-white px-4 py-3 text-xs text-slate-500"><LockKeyhole className="h-4 w-4 text-[#087f78]" />Fonds logiquement ségrégués</div></header>
    <div className="mt-7 grid gap-4 md:grid-cols-2"><WalletCard currency="USD" balance={walletFor("USD")} onDeposit={() => { setCurrency("USD"); setDialog("deposit"); }} onWithdraw={() => { setCurrency("USD"); setDialog("withdrawal"); }} /><WalletCard currency="CDF" balance={walletFor("CDF")} onDeposit={() => { setCurrency("CDF"); setDialog("deposit"); }} onWithdraw={() => { setCurrency("CDF"); setDialog("withdrawal"); }} /></div>
    <div className="mt-7 grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><Card className="rounded-2xl border-slate-200 bg-white"><CardHeader><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">Traçabilité</p><CardTitle className="mt-2 text-xl text-[#0a2233]">Demandes récentes</CardTitle></div><Banknote className="h-5 w-5 text-[#087f78]" /></div></CardHeader><CardContent className="space-y-3"><RequestList title="Dépôts" rows={requests?.deposits ?? []} icon={<ArrowDownLeft className="h-4 w-4" />} /><RequestList title="Retraits" rows={requests?.withdrawals ?? []} icon={<ArrowUpRight className="h-4 w-4" />} /></CardContent></Card><Card className="rounded-2xl border-0 bg-[#0a2233] text-white"><CardHeader><CardTitle className="text-xl font-medium">Avant toute demande</CardTitle></CardHeader><CardContent className="space-y-4 text-sm leading-6 text-slate-300"><div className="flex gap-3"><ShieldCheck className="mt-1 h-4 w-4 shrink-0 text-[#e6b93f]" /><p>Votre identité et votre profil de risque doivent être validés avant l’accès aux mouvements financiers.</p></div><div className="flex gap-3"><Clock3 className="mt-1 h-4 w-4 shrink-0 text-[#e6b93f]" /><p>Chaque demande est journalisée, réconciliée et peut être soumise à un contrôle conformité.</p></div><div className="rounded-2xl border border-[#e6b93f]/20 bg-[#e6b93f]/10 p-4 text-xs text-[#f7e0a4]">Les actions de cet écran sont enregistrées et contrôlées. Les transferts seront disponibles après validation du partenaire de paiement.</div></CardContent></Card></div>
    <Dialog open={Boolean(dialog)} onOpenChange={open => !open && setDialog(null)}><DialogContent className="rounded-2xl border-[#dce4e5] bg-[#f7f7f2] text-[#0a2233] shadow-[0_24px_80px_rgba(7,26,42,.28)] sm:max-w-md"><DialogHeader><DialogTitle className="text-[#0a2233]">{dialog === "deposit" ? "Créer une demande de dépôt" : "Créer une demande de retrait"}</DialogTitle><DialogDescription>Devise sélectionnée : {currency}. Une validation conformité sera requise.</DialogDescription></DialogHeader><div className="flex gap-2">{(["USD", "CDF"] as const).map(code => <Button key={code} onClick={() => setCurrency(code)} className={currency === code ? "bg-[#0a2233] text-white" : "bg-slate-100 text-slate-600 hover:bg-slate-200"}>{code}</Button>)}</div><div><label className="text-xs font-medium text-slate-600">Montant</label><Input type="number" min="0.01" step="0.01" value={amount} onChange={event => setAmount(event.target.value)} placeholder="0.00" className="mt-2" /></div><DialogFooter><Button disabled={!Number(amount) || deposit.isPending || withdrawal.isPending} onClick={() => dialog === "deposit" ? deposit.mutate({ amount: Number(amount), currency, method: "partner", idempotencyKey: crypto.randomUUID() }) : withdrawal.mutate({ amount: Number(amount), currency, destinationType: "partner", idempotencyKey: crypto.randomUUID() })} className="w-full bg-[#0a2233] text-white hover:bg-[#0d2638]">{dialog === "deposit" ? "Enregistrer la demande" : "Soumettre au contrôle"}</Button></DialogFooter></DialogContent></Dialog>
  </div></div>;
}
function WalletCard({ currency, balance, onDeposit, onWithdraw }: { currency: string; balance: any; onDeposit: () => void; onWithdraw: () => void }) { return <Card className={`rounded-2xl border-0 shadow-sm ${currency === "USD" ? "bg-[#0a2233] text-white" : "border-[#b9ded4] bg-[#e9f6f2] text-[#0a2233]"}`}><CardContent className="p-6"><div className="flex items-start justify-between"><div><p className={`text-xs font-semibold uppercase tracking-[0.2em] ${currency === "USD" ? "text-[#e6b93f]" : "text-[#087f78]"}`}>Portefeuille {currency}</p><p className="mt-4 text-4xl font-semibold tracking-tight">{Number(balance.availableBalance).toLocaleString("fr-FR", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} <span className="text-lg font-medium opacity-60">{currency}</span></p><p className={`mt-2 text-xs ${currency === "USD" ? "text-slate-400" : "text-slate-500"}`}>Disponible · {Number(balance.pendingBalance).toFixed(2)} en attente</p></div><div className={`grid h-11 w-11 place-items-center rounded-2xl ${currency === "USD" ? "bg-white/10 text-[#e6b93f]" : "bg-white/70 text-[#087f78]"}`}><WalletCards className="h-5 w-5" /></div></div><div className="mt-7 flex gap-2"><Button onClick={onDeposit} className={currency === "USD" ? "bg-[#e6b93f] text-[#0a2233] hover:bg-[#f7e0a4]" : "bg-[#0a2233] text-white hover:bg-[#0d2638]"}><ArrowDownLeft className="mr-2 h-4 w-4" />Déposer</Button><Button onClick={onWithdraw} variant="outline" className={currency === "USD" ? "border-white/20 bg-transparent text-white hover:bg-white/10" : "border-[#087f78]/30 bg-transparent text-[#087f78] hover:bg-white/70"}><ArrowUpRight className="mr-2 h-4 w-4" />Retirer</Button></div></CardContent></Card>; }
function RequestList({ title, rows, icon }: { title: string; rows: any[]; icon: React.ReactNode }) { return <div className="rounded-2xl border border-slate-100 p-4"><div className="flex items-center gap-2 text-sm font-semibold text-[#0a2233]">{icon}{title}</div>{rows.length ? rows.slice(0, 4).map(row => <div key={row.id} className="mt-3 flex flex-wrap items-center gap-x-2 gap-y-2 border-t border-slate-100 pt-3 text-xs"><span className="min-w-0 flex-1 truncate text-slate-500">{row.reference}</span><Badge variant="outline">{row.status}</Badge><span className="shrink-0 font-medium text-[#0a2233]">{row.amount} {row.currency}</span></div>) : <p className="mt-3 text-xs text-slate-400">Aucune demande enregistrée.</p>}</div>; }
